# Generated by Django 5.1.2 on 2024-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="содержимое")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="изображение",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True, null=True)),
                (
                    "views_counter",
                    models.IntegerField(
                        default=0, verbose_name="количество просмотров"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="признак публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
