# Generated by Django 5.1.2 on 2024-10-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="признак публикации"),
        ),
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите номер версии",
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите название версии",
                        max_length=50,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "current_version_indicator",
                    models.BooleanField(
                        default=True, verbose_name="признак публикации"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="version",
                        to="catalog.product",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["version_name", "version_number"],
            },
        ),
    ]
