# Generated by Django 4.2.2 on 2024-10-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "created_at"],
                "permissions": [
                    ("set_published", "Can publish product"),
                    ("edit_description", "Can edit description"),
                    ("change_category_product", "Can change category of product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
